import type { Metadata } from "next";
import "@fontsource/roboto/300.css";
import "@fontsource/roboto/400.css";
import "@fontsource/roboto/500.css";
import "@fontsource/roboto/700.css";
import "./globals.css";
import Header from "@/Components/Header";
import Footer from "@/Components/Footer";
import TanstackProvider from "@/Components/Provider/TanstackProvider";

export const metadata: Metadata = {
  title: "Shoe Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
       <TanstackProvider>
           <Header />
           {children}
           <Footer />
       </TanstackProvider>
      </body>
    </html>
  );
}
