import type { Metadata } from "next";
import { cookies } from "next/headers";
import "@fontsource/roboto/300.css";
import "@fontsource/roboto/400.css";
import "@fontsource/roboto/500.css";
import "@fontsource/roboto/700.css";
import "./globals.css";
import TanstackProvider from "@/Components/Provider/TanstackProvider";
import UserLayout from "@/layouts/UserLayout";
import AppProvider from "./context/AppProvider";
import { ACCESS_TOKEN } from "@/utils/setting";

export const metadata: Metadata = {
  title: "Shoe Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const cookieStore = cookies();
  const accessToken = cookieStore.get(ACCESS_TOKEN)?.value ?? "";

  return (
    <html lang="en">
      <body suppressHydrationWarning>
        <TanstackProvider>
          <AppProvider initialValue={accessToken}>
            <UserLayout>
              {children}
            </UserLayout>
          </AppProvider>
        </TanstackProvider>
      </body>
    </html>
  );
}