import type { Metadata } from "next";
import "@fontsource/roboto/300.css";
import "@fontsource/roboto/400.css";
import "@fontsource/roboto/500.css";
import "@fontsource/roboto/700.css";
import "./globals.css";
import TanstackProvider from "@/Components/Provider/TanstackProvider";
import UserLayout from "@/layouts/UserLayout";

export const metadata: Metadata = {
  title: "Shoe Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <TanstackProvider>
          <UserLayout>
            {children}
          </UserLayout>
        </TanstackProvider>
      </body>
    </html>
  );
}
